first version
GreenNerd/vue-components-gulp pull request #2
Opened 2017-02-21 07:01 UTC by Leecason

complete all features.

2017-02-21 11:38 UTC, moonRider requested changes

2017-02-21 11:38 UTC, moonRider commented on src/alertify/alertify-demo.coffee
> +document.querySelector('.btn-success').addEventListener('click', () ->
addEventListener需要3个参数，你去学习下，然后把这里改了

2017-02-21 11:38 UTC, moonRider commented on src/alertify/alertify.coffee
> +      el: '.alert-box-wrapper'
这里不建议用这个传一个选择器的方式，改用生成的dom节点是不是要好些

2017-02-21 11:38 UTC, moonRider commented on src/alertify/alertify.coffee
> +             'alert-success': type === 'success',
如果这里定义了10个状态，这样写是不是很蛋疼？

2017-02-21 11:38 UTC, moonRider commented on src/alertify/alertify.coffee
> +      @start_time = new Date()
L56-L60 是不是有些似曾相识了？

2017-02-21 11:38 UTC, moonRider commented on src/alertify/alertify.scss
> +  .alert-mask {
这个已经不存在了

2017-02-21 11:38 UTC, moonRider commented on src/alertify/alertify.scss
> +button {
这个组件是会被拿出去使用的，button的重置并不属于这个。你把button的相关代码分出去

2017-02-21 11:39 UTC, moonRider commented
@Leecason  把上面的都看看，该改的就改一下

2017-02-21 11:59 UTC, Leecason commented
好的，谢谢！！

2017-02-22 04:16 UTC, moonRider requested changes

2017-02-22 04:16 UTC, moonRider commented on src/alertify/alertify.coffee
> +      now_time = new Date()
now_time 和后米的 left_time 都只用过一次吧？可以不用临时变量

2017-02-22 04:16 UTC, moonRider commented on src/alertify/alertify.coffee
> +      Alertify.instance = false
用 null 比 false 好，null 可以让垃圾回收收回内存

2017-02-22 04:21 UTC, moonRider commented
@Leecason  注意换行，methods里面的属性和属性间需要换1行，methods，computed，created这一级的间隔也是一行。以后读起来也比较清晰

2017-03-07 08:06 UTC, merged